### ISSUE TITLE
Indents don't count against line length

### ISSUE THREAD

**Issue by karlstolley** [mirnovov/hardwrap#1]
Hi! First of all, a huge thanks for writing this plugin.

One issue that I've noticed is that, while indents are respected (which is awesome), they do not count against the overall line length.

For example, if I'm wrapping lines at 100 characters but I have 4 spaces of indent, the longest line after your plugin runs will go out to 104 characters.

I've had a look at your plugin code, and I think I can fix this, but I thought I'd file an issue and make sure that a) you'd welcome the contribution and b) that you didn't have something like this started already.

Thanks!

**Comment by mirnovov** [comment]
Thanks for the offer, but I had already been aware of the issue and I've whipped up a quick fix already before I properly read the description haha.

It even takes into account tab length, let me know if that's not desired behaviour and I'll add an option to remove it.
